### PR TITLE
fix(test): Use explicit `typing` objects for containers

### PR DESCRIPTION
**Pull request by jrwrigh**
- Using `list[str]` for type hints is incompatible with Python 3.7.9 (at least, possibly with newer versions as well)

Error reported by @KennethEJansen . TBH, I didn't even know that Python allowed to use `tuple/list` directly in type hints like that. I guess we're paying the burden of them not doing the obvious thing to begin with.

### CODE REVIEW

**Comment by zatkins-dev** [comment]
I guess that form of type annotation was added in 3.9, so we can use the old `List` version for backward compatibility. 

Still, I would like to set a hard limit on what version of Python we support.

**Comment by zatkins-dev** [comment]
Specifically, `dataclasses` was added in 3.7, so I would like to not support anything older than that.

**Review by zatkins-dev — APPROVED** [review]
Looks good to me!

**Comment by jedbrown** [comment]
PETSc uses [vermin](https://pypi.org/project/vermin/) to check that Python syntax is supported by all the versions we target.

**Review by jedbrown — APPROVED** [review]
Thanks for the quick fix.

**Comment by jeremylt** [comment]
Can you make the same PR in Ratel?

**Comment by jrwrigh** [comment]
Sure.

**Pull request merged**
