### PR TITLE
Jed/config

### PR DESCRIPTION
**Pull request by jedbrown**
I think this supersedes #422 if you agree about the caching strategy.

### CODE REVIEW

**Comment by jedbrown** [comment]
@v-dobrev Do you have any objections to this strategy? I'd like to give you chance to weigh in if you'd like before merging.

**Comment by v-dobrev** [comment]
@jedbrown, it looks like this PR addresses the issue from #422 and does a lot more on top of that. Looks good to me.

In the mean time I was using the following patch which resolved the issue I had with `-fopenmp-simd` on Mac with older Apple Clang. Also it switches the AVX flag on Mac to enable the avx backend there -- I'm not sure if this is an issue with newer Apple Clang versions. Feel free to include any of these if you think they might be useful to others.

```diff
diff --git a/Makefile b/Makefile
index 26482133..70b203be 100644
--- a/Makefile
+++ b/Makefile
@@ -73,7 +73,10 @@ endif
 # export LSAN_OPTIONS=suppressions=.asanignore
 AFLAGS = -fsanitize=address #-fsanitize=undefined -fno-omit-frame-pointer
 
-OPT    = -O -g -march=native -ffp-contract=fast -fopenmp-simd
+OMP_SIMD_FLAG = -fopenmp-simd
+OMP_SIMD_FLAG := $(if $(shell $(CC) $(OMP_SIMD_FLAG) -E - < /dev/null \
+  &> /dev/null && echo OK),$(OMP_SIMD_FLAG))
+OPT    = -O -g -march=native -ffp-contract=fast $(OMP_SIMD_FLAG)
 CFLAGS = -std=c99 $(OPT) -Wall -Wextra -Wno-unused-parameter -fPIC -MMD -MP
 CXXFLAGS = -std=c++11 $(OPT) -Wall -Wextra -Wno-unused-parameter -fPIC -MMD -MP
 NVCCFLAGS = -ccbin $(CXX) -Xcompiler "$(OPT)" -Xcompiler -fPIC
@@ -283,7 +286,8 @@ endif
 
 # AVX Backed
 AVX_STATUS = Disabled
-AVX := $(shell $(CC) $(OPT) -v -E - < /dev/null 2>&1 | grep -c ' -mavx')
+AVX_FLAG := $(if $(DARWIN),+avx,-mavx)
+AVX := $(shell $(CC) $(OPT) -v -E - < /dev/null 2>&1 | grep -c ' $(AVX_FLAG)')
 ifeq ($(AVX),1)
   AVX_STATUS = Enabled
   libceed.c += $(avx.c)
```

**Comment by jeremylt** [comment]
Avx isn't running on Travis even though the chip supports Avx, so this patch would be helpful.

**Comment by jedbrown** [comment]
I believe I've resolved these issues in cf4a56af4169f819d37a2d29f5bb42c69b6f7d23, which we can merge once the pipeline passes. I also noticed that we aren't using FMA instructions when available, so have dropped that in #476.

**Pull request merged**
