### PR TITLE
fluids: Change SmartSim sizeInfo to show minimum global array size

### PR DESCRIPTION
**Pull request by jrwrigh**
@rickybalin I'm having trouble getting this to run locally with MPI for whatever reason, but this should do what we talked about.

### CODE REVIEW

**Comment by jrwrigh** [comment]
I got it tested this morning and it works as expected. 


The issue I was having: `{"-n", 2}` is a set, but `{"-n": 2}` is a dictionary. I used to be really good at Python, I swear. :facepalm:

**Review by jeremylt — APPROVED** [review]
Seems ready?

**Comment by jeremylt** [comment]
Ready to merge?

**Comment by jrwrigh** [comment]
Note quite. I'll merge it in when we have it tested; ran into issues with building on Sunspot, but I think those are mostly ironed out now.

**Comment by rickybalin** [comment]
Tested on Sunspot and it works as expected. Everything looks good to merge on my end. Thanks!

**Pull request merged**
