### PR TITLE
Example leaks

### PR DESCRIPTION
**Pull request by jeremylt**
Fixing memory leaks in the examples, ~~hopefully helps with the HIP tests on Noether~~

Checked
- `examples/ceed`
- `examples/dealii`
- `examples/fluids`
- `examples/mfem`
- `examples/nek`
- `examples/petsc`
- `examples/solids`

### CODE REVIEW

**Comment by rezgarshakeri** [comment]
I saw one for loop using `CeedInt`, any reason why it is not `PetscInt`?

**Comment by jeremylt** [comment]
Which loop? I don't see a loop starting with `for (CeedInt...)`?

**Comment by rezgarshakeri** [comment]
https://github.com/CEED/libCEED/pull/1651/files#diff-b9ec863dad1f654f6b87f7fe59d030831acfcd35d6331fb85b58a60073bd4417L184

**Comment by jeremylt** [comment]
Ah. No clue. It wasn't part of the diff so I didn't notice it.

**Pull request merged**
