### PR TITLE
Add a diffusion example with MFEM + libCEED

### PR DESCRIPTION
**Pull request by v-dobrev**
This branch adds an MFEM + libCEED version of BP3: examples/ex3.cpp.

### CODE REVIEW

**Comment by tzanio** [comment]
Very nice, thanks @v-dobrev!

**Comment by jedbrown** [comment]
We've been sloppy about ADD vs INSERT semantics. In normal finite-element procedures, we tend to use INSERT for applying the operator and ADD for the transpose. Should we add an argument to `Ceed*Apply` or generalize `CeedTransposeMode`?

**Comment by v-dobrev** [comment]
It is probably best to generalize Apply to perform `y = a*A*x+b*y` and `y = a*A^T*x+b*y`.

**Comment by jedbrown** [comment]
Hmm, in what sparse algorithms do we need general `a`? It's easier to call with one parameter than with two, and there are circumstances where general `a` would restrict optimization. For example, merely applying `y = a A^T x` where `A` is CSR involves an extra multiply for each entry rather than once per row.

**Comment by v-dobrev** [comment]
My thinking is that the cost of multiplying with `a` and `b`, regardless of the operator representation, will be negligible compared to the action of the matrix. Also, cases like `a = 1` can be specialized, if there is any need. In the example you mention, `y = a A^T x` for CSR `A`, I think you can simply scale `x` by `a` (on the fly) - you always scale the vector that is traversed in the outer loop - in the case of `y = a A x` it is `y`.

Anyway, I'm not 100% convinced myself what the best option is, so I'm flexible. What is your preference? Is it `y = A x + b y` and `y = A^T x + b y`?

Also, do you want me to make the update in this branch?

**Comment by jedbrown** [comment]
We can't modify the vector, though I think you mean to do that when loading into registers; you're right that the general case is not a lot more work. But it is some extra complexity in the implementation and I can't think of a practical case where assuming `a=1` would result in performance degradation (e.g., by making extra passes over data). I raised the issue in this thread because you added this `Add` concept and I think it's better to make it consistent. We can either merge this PR with an immediate plan to introduce that concept consistently or introduce it before merging. What's your preference?

**Comment by v-dobrev** [comment]
The additions I made are internal to the two backends. So, I think we can merge this and start a separate branch for the front-end changes. (It is my understanding that we are talking about front-end changes.)

**Pull request merged**
