### PR TITLE
Follow up on PR #52

### PR DESCRIPTION
**Pull request by v-dobrev**
Some small tweaks and improvements in the MFEM and PETSc examples.

### CODE REVIEW

**Comment by jedbrown** [comment]
Looks good in general. Unfortunately, this dependency strategy causes `make -B` to always fail (erroneously claiming that `PETSC_DIR` and `PETSC_ARCH` need setting).

Also, is it intentional that `make` in examples/mfem always rebuilds both executables, even when there are no changes? (It's because `okl-lib-cache` is a phony target.)

**Comment by tzanio** [comment]
I will keep the OCCA caching commands for now. At a minimum, comment it out instead of deleting it.

**Comment by v-dobrev** [comment]
I'll try it out in a moment.

@camierjs, what do you think? Should we remove the caching and rely on `dladdr` instead?

**Comment by jedbrown** [comment]
I see valgrind errors.  Will try to debug.

**Comment by jedbrown** [comment]
f4ffd59138ac341f85d05e2ebaab3e100b114fff (on 'master' now) plus the following gives me valgrind-clean results.

```
diff --git i/examples/mfem/bp1.cpp w/examples/mfem/bp1.cpp
index f6c0e90..0e23a1e 100644
--- i/examples/mfem/bp1.cpp
+++ w/examples/mfem/bp1.cpp
@@ -135,6 +135,7 @@ int main(int argc, char *argv[]) {
   }
 
   // 11. Free memory and exit.
+  mass.~CeedMassOperator();
   delete fespace;
   delete fec;
   delete mesh;
```

**Comment by jedbrown** [comment]
I believe all memory errors are now fixed by #59, without need for the explicit destructor above.

**Comment by v-dobrev** [comment]
Hmm, I cannot reproduce the issue in master but that OK. I get a bunch of leaks from cuda which happens even if I do not use an OCCA backend - maybe we need to postpone the OCCA init until we actually need it.

**Comment by jedbrown** [comment]
`CeedInit_Occa` is not called unless you select an Occa backend. I think your observed memory leaks may come from static constructors via Occa.

**Comment by v-dobrev** [comment]
Everyone, take a look at my last update and let me know if something is not right.

@jedbrown, I spoke to @camierjs and @tzanio offline and they agreed to removing the kernel caching from the makefiles.

**Comment by jedbrown** [comment]
Germane to this PR, can we resolve the conversation about `dladdr`? Is it okay to remove the occa caching in the makefiles?

@camierjs Can you respond to this? https://github.com/CEED/libCEED/pull/54#issuecomment-377355848

**Comment by jedbrown** [comment]
Thanks, merging now.

**Pull request merged**
