### PR TITLE
Operator active data

### PR DESCRIPTION
**Pull request by jeremylt**
This PR

- explicitly makes `CeedOperatorGetActiveElemRestriction` and `CeedOperatorGetActiveBasis` for non-composite operators
- adds `CeedOperatorGetActiveVectorLengths`

### CODE REVIEW

**Comment by v-dobrev** [comment]
This PR helped me resolve some issues in https://github.com/mfem/mfem/pull/2569. Thanks!

**Review by jedbrown — APPROVED** [review]
Looks good. Do we currently check when creating a composite operator that the active vector lengths match?

**Comment by jeremylt** [comment]
I updated to more robustly check for sub-operator compatibility. I had thought we had this already, but its a good thing to have now.

**Comment by jedbrown** [comment]
Great, thanks @v-dobrev

**Comment by jeremylt** [comment]
Sorry for the extra noise with force pushes - I forgot an edge case in the compatibility checking. This check moves up an error that would have been caught when the operator was applied, so it should just provide nicer error messages for future development and should have no impact on current code that works already.

**Comment by tzanio** [comment]
Any chance this could be merged today?

**Comment by jedbrown** [comment]
I think it'll merge as soon as this CI run passes. We've both approved. @jeremylt I could add another Noether "slot" for non-GPU runs so they don't get as backed up as they are now.

**Pull request merged**
