### PR TITLE
Small fixes from Python Work

### PR DESCRIPTION
**Pull request by jeremylt**
These are small fixes we've found in the Python branch that should be isolated from the work there. @valeriabarra, I'll cherry-pick your t3* scientific notation fixes into here when I get a chance.

### CODE REVIEW

**Comment by jeremylt** [comment]
Ready for review/approval/merge

**Comment by jeremylt** [comment]
@valeriabarra, it looks like some python files snuck in with a couple of your commits

**Comment by valeriabarra** [comment]
Sorry! Not intentional!

You can go ahead and revert those, please, if you can.

**Comment by valeriabarra** [comment]
> @valeriabarra, it looks like some python files snuck in with a couple of your commits? Or at least some references to them?

Removed them.

**Comment by jeremylt** [comment]
I added some doc fixes I found when working on the docstrings

**Comment by jeremylt** [comment]
Now that the python interface is basically done, I believe we're good to merge this.

**Pull request merged**
