### PR TITLE
Solids - Current configuration update 

### PR DESCRIPTION
**Pull request by rezgarshakeri**
Recently we used `computeDetF` function to compute `J=det(F)`. However, we can compute it using `det(C)`.

### CODE REVIEW

**Comment by rezgarshakeri** [comment]
It seems `sqrt` function is much more expansive than using `computeDetF`

**Comment by jeremylt** [comment]
Which optimization flags? I'd be curious to play around and understand whats going on.

**Comment by jedbrown** [comment]
In the constitutive model, we often only need `log(J) = log1p(detCm1) / 2`. Note that when we're in the current configuration, it's unnatural to compute C, but detC = detb.

For numerical stability, I'd prefer to formulate in terms of what I might call a "left Green-Lagrange strain", `e = (b - I)/2`. It serves the same role as the Green-Lagrange strain, simplifies CRs, and avoids numerical stability issues that arise when working directly with `b`. For example, Neo-Hookean in the current configuration is `\tau = \lambda \log J I + 2 \mu e`. (I'm not aware of a name for this tensor. The Almansi tensor plays a similar role, but needs `b^{-1}`, which is inconvenient for constitutive modeling.)

**Comment by rezgarshakeri** [comment]
> Which optimization flags? I'd be curious to play around and understand whats going on.

Arsh checked in Noether with one of his meshes. Would you please try with dmplex:
`mpiexec -n 2 ./elasticity -nu 0.3 -E 20 -degree 1 -dm_plex_box_faces 10,10,10 -problem FSCurrent-NH1 -num_steps 15 -bc_clamp 3 -bc_traction 4 -bc_traction_4 0,0,-1 -snes_linesearch_type cp`

right now in main we use `J=computeDetF` function and in this branch we use `sqrt`

**Comment by rezgarshakeri** [comment]
> In the constitutive model, we often only need `log(J) = log1p(detCm1) / 2`. Note that when we're in the current configuration, it's unnatural to compute C, but detC = detb.
> 
> For numerical stability, I'd prefer to formulate in terms of what I might call a "left Green-Lagrange strain", `e = (b - I)/2`. It serves the same role as the Green-Lagrange strain, simplifies CRs, and avoids numerical stability issues that arise when working directly with `b`. For example, Neo-Hookean in the current configuration is `\tau = \lambda \log J I + 2 \mu e`. (I'm not aware of a name for this tensor. The Almansi tensor plays a similar role, but needs `b^{-1}`, which is inconvenient for constitutive modeling.)

yes, we used `log(J) = log1p(detCm1) / 2`, but in current configuration we need `F^{-1}` to map qdata from initial to current. And we need `det(F)` to compute `F{-1}`

**Comment by ArashMehraban** [comment]
I'd appreciate it if nothing is checked on Noether now. I am running a bunch of stuff using 32 and 64 procs.

**Comment by ArashMehraban** [comment]
BTW, FSCurrent-NH2 is not 50% faster than other algorithms! That is what I am checking now. It might be in the realm of 2%-15% with large deformation runs. I realized all of our tests were on a  small strain scale. For an actual large deformation problem  2%-15% appear to be achievable.

**Comment by rezgarshakeri** [comment]
> Which optimization flags? I'd be curious to play around and understand whats going on.

sorry I forgot to say we used `make OPT="-O3 -march=native"`

**Comment by jeremylt** [comment]
Ah. Are the current runs using `-funsafe-math-optimizations`? We saw a performance impact with that flag the other day.

**Comment by rezgarshakeri** [comment]
> Ah. Are the current runs using `-funsafe-math-optimizations`? We saw a performance impact with that flag the other day.

yeah, we used `PETSc_DIR=/projects/petsc` on noether which uses `-funsafe-math-optimizations`.

**Comment by jeremylt** [comment]
Yea, but was the solids example also compiled with those flags? The QFunction has a lot of flops in it

**Comment by rezgarshakeri** [comment]
> Yea, but was the solids example also compiled with those flags? The QFunction has a lot of flops in it

no just, `make OPT="-O3 -march=native"`

**Comment by jeremylt** [comment]
Hmm. I wonder if there is any performance difference when compiling with everything with those math ops. I suppose the only way to know is to check.

**Comment by rezgarshakeri** [comment]
yeah, lets Arash finishes his run, we will check this week hopefully

**Comment by jedbrown** [comment]
`make V=1` shows the complete compile command, which I believe contains all the flags from PETSc plus the extra flags you pass in `OPT='-O3 -march=native'`. I would not expect an issue with compiler flags in what we've just discussed.

**Comment by jedbrown** [comment]
Ideally, we would compute `Jm1 = det(F) - 1` stably from `\nabla_X u` and then _not_ need to compute the determinant of `C` or `b`.

**Comment by jeremylt** [comment]
Huh, so was a lot of the speed change we say the other day in the vector-vector ops in PETSc?

**Comment by jedbrown** [comment]
No, basically none there. The big differences were in qfunction vectorization. Now it's problem size dependent memory consequences.

**Pull request closed without merging**
