### PR TITLE
Jed/petsc 3.14 gcc 10

### PR DESCRIPTION
**Pull request by jedbrown**
Add support for petsc-3.14 and fix Fortran bugs reported by gfortran-10.

### CODE REVIEW

**Comment by valeriabarra** [comment]
I think [travis](https://github.com/CEED/libCEED/blob/master/.travis.yml) will need to be updated as well

**Comment by valeriabarra** [comment]
I don't see the [13.4 tag](https://gitlab.com/petsc/petsc/-/tags) though. Has it been released yet?

**Comment by jedbrown** [comment]
I guess you're asking about 3.14, which isn't expected until September.

**Comment by valeriabarra** [comment]
> I guess you're asking about 3.14, which isn't expected until September.

Lol! I was misreading.. haha yes... my low vision always bites me

**Comment by valeriabarra** [comment]
There is a `make style` change in Travis which you can run to avoid, and a failure in `petsc-bpsraw /omp/occa` which happens very often but strangely not always. I saw it in #516 but not in #536

**Comment by jedbrown** [comment]
Seems to just be the `bpsraw` with `/omp/occa` on non-x86 issue, which will hopefully be resolved for good in #305.

**Pull request merged**
