### PR TITLE
Add all backends to Doxygen

### PR DESCRIPTION
**Pull request by jeremylt**
This is a small PR to fix the fact that Doxygen currently misses half of our backends.

### CODE REVIEW

**Comment by jeremylt** [comment]
I was thinking about that. I organized them by 'backend family', i.e. the CPU backends are grouped, the CUDA backends are grouped, etc. I'm fine with whatever organizational schema makes the most sense to the most people.

**Comment by valeriabarra** [comment]
Since in this list the family label (`/cpu/` or `/gpu/`) is not present, I'd keep them in alphabetic order for easy future insertions/deletions.

**Comment by jeremylt** [comment]
Fair enough; changed

**Comment by valeriabarra** [comment]
Would this recursive alphabetization make it extremely pedantic? Or just tidier?
```
                         . \
                         backends/avx \
                         backends/blocked \
                         backends/cuda \
                         backends/cuda-reg \
                         backends/cuda-shared \
                         backends/magma \
                         backends/memcheck \
                         backends/occa \
                         backends/opt \
                         backends/ref \
                         backends/template \
                         backends/xsmm \
                         doc \
                         include \
                         interface \
                         examples/ceed \
                         examples/mfem \
                         examples/nek5000 \
                         examples/petsc \
                         examples/navier-stokes \
                         tests \
```

**Comment by jeremylt** [comment]
I left it alone because the original ordering is roughly ordered by line length, but I have no opinion either way.

**Pull request merged**
