### PR TITLE
fluids: Fix 64bit Int typing issues

### PR DESCRIPTION
**Pull request by jrwrigh**
Accidentally leaked a few issues with handling 64bit `PetscInt` here, so addressing that here.

### CODE REVIEW

**Review by jeremylt — APPROVED** [review]
LGTM

note - I might have to re-approve after the style fix

**Comment by jrwrigh** [comment]
Yeah, not sure about that style fix. My local clang-format seems indifferent to the change. In fact, it doesn't seem to edit the fluids files at all with `make format-c`...

**Comment by jeremylt** [comment]
This is failing in CI on main

**Comment by jrwrigh** [comment]
Ah, forgot that `IntArrayC2P` frees the input array. I need both the `PetscInt` and `CeedInt` versions of the array.

**Pull request merged**
