### PR TITLE
[Julia] Improvements to configuration documentation and build step

### LINKED ISSUE #759: Configuring LibCEED.jl instructions
Not sure if the reference to the "Configuring LibCEED.jl" section [here](https://github.com/CEED/libCEED/tree/main/julia/LibCEED.jl) is supposed to link to the following section in the same file, but if I click on it I see a 404.

### LINKED ISSUE #760: Configuring LibCEED.jl providing JULIA_LIBCEED_LIB
I'm reporting on the difficulties mentioned earlier on configuring `LibCEED.jl` . 
Since I already have libCEED binary built from source, I was following the [`Configuring LibCEED.jl`](https://github.com/CEED/libCEED/tree/main/julia/LibCEED.jl#configuring-libceedjl) instructions. I attempted both ways described in the instructions but both fail with same error message basically `LibCEED (not found in project or manifest)`

```
$ cd libCEED
$ make -B
```
the library builds just fine. Then I proceed with the first way:

1. 
```
$ JULIA_LIBCEED_LIB=/home/valeria/CEED/libCEED/lib julia
              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.4 (2021-03-11)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> build LibCEED
ERROR: The following package names could not be resolved:
 * LibCEED (not found in project or manifest)
```

Or second way:

2. 
```
julia> using Pkg

julia> withenv("JULIA_LIBCEED_LIB" => "/home/valeria/CEED/libCEED/lib") do
       Pkg.build("LibCEED")
       end
ERROR: The following package names could not be resolved:
 * LibCEED (not found in project or manifest)

Stacktrace:
 [1] pkgerror(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52
 [2] ensure_resolved(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; registry::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:837
 [3] ensure_resolved at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:802 [inlined]
 [4] build(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; verbose::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:744
 [5] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:729 [inlined]
 [6] #build#69 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [7] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [8] #build#68 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
 [9] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
 [10] build(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65
 [11] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65 [inlined]
 [12] #3 at ./REPL[4]:2 [inlined]
 [13] withenv(::var"#3#4", ::Pair{String,String}) at ./env.jl:161
 [14] top-level scope at REPL[4]:1
```

cc: @pazner 
Thanks for any pointers.

### PR DESCRIPTION
**Pull request by pazner**
Resolves #759.
Resolves #760.

### CODE REVIEW

**Review by valeriabarra — APPROVED** [review]

**Review by jedbrown — APPROVED** [review]

**Comment by valeriabarra** [comment]
I attempted a rewording. Hopefully it's clearer to others, too

**Comment by valeriabarra** [comment]
Feel free to disregard my commit if not

**Comment by valeriabarra** [comment]
If kept, I think this will resolve #760 too and I will close it, if not automatically closed

**Comment by pazner** [comment]
Looks good, I just changed the wording very slightly.

I also changed the build step to error if given a path that does not point to a real file (and not a directory), cf. [this comment](https://github.com/CEED/libCEED/issues/760#issuecomment-828852615).

**Comment by jeremylt** [comment]
The readthedocs build should pass if this branch is rebased off of main.

**Pull request merged**
