### PR TITLE
Use more `__restrict__` in `cuda-gen` backend.

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR generalizes the usage of `__restrict__` to all inputs that can benefit from it.

### CODE REVIEW

**Comment by jedbrown** [comment]
Any performance consequences? Do we need to get this into qfunctions as well?

**Comment by YohannDudouit** [comment]
I think it only makes sense where we read from device memory, which is not the case for QFunctions where the data has already been loaded into registers. I haven't done any benchmarking at the moment.

**Review by jedbrown — APPROVED** [review]
Looks good. Would you mind making a note about `restrict` semantics in developer notes (doc/sphinx/source/libCEEDdev.rst) and do some minor performance comparison to see if it makes any difference. If it does, we should mention it in release notes.

**Comment by jeremylt** [comment]
This PR just needs the documentation notes, right?

**Comment by jedbrown** [comment]
Yes, I'd meant to circle back and test it myself. It'd be nice to know if there's any impact, but the implication on aliasing should be communicated. It might help to use `restrict` in QFunctions also for CPU. We've been seeing good code without thus far and thus I've omitted it, but I could imagine it affecting code size and/or speed when there are more inputs/outputs.

**Comment by jeremylt** [comment]
I did do some benchmarking on Lassen: https://github.com/CEED/libCEED/tree/jeremy/cuda-gen/restrict

**Comment by YohannDudouit** [comment]
@jed @jeremylt I will try to get to this soon.

**Comment by YohannDudouit** [comment]
> I did do some benchmarking on Lassen: https://github.com/CEED/libCEED/tree/jeremy/cuda-gen/restrict

Are you sure this is the right link?

**Comment by jeremylt** [comment]
Should be. It has your commit 359613d7e4c8b7f55ddd77690d954abe28f7bc88 and my data b9c872237ce4d53b369bd28d265e3afd8d8590b2

**Review by jedbrown — APPROVED** [review]
This has no performance impact that I can tell, but I think it's still fair to add.

I've added a note to the docs and will merge if you think it's adequate.

**Pull request merged**
