### PR TITLE
CI - Use GitHub Actions

### LINKED ISSUE #652: Evaluate Travis or move CI away
The new pricing model has limited credit for open source so we may either need to start paying or move elsewhere (presumably GitHub Actions and/or GitLab-CI).

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

### PR DESCRIPTION
**Pull request by jeremylt**
This PR shifts our CI to GitHub actions and increases the testing on Noether.

Closes #652 

ToDo:
- [x] Migrate Julia docs build to GitHub Actions
- [x] Fix filepath error for Nek5000 on Noether
- [x] Drop Travis requirement in repo settings

### CODE REVIEW

**Comment by jeremylt** [comment]
OK, I have:

GitHub Actions
- Test [gcc-9, clang] on [ubuntu, osx]
- Test [gcc-9] on [ubuntu] with [aarch64, ppc64le]
- Test style
- Test Python with style
- Test Julia with style

GitLab CI
- Test [hipMAGMA, LIBXSMM, OCCA, Valgrind] backends with [MFEM, Nek5000]
- CodeCov

Azure Pipelines
- Test base libCEED with PETSc

The big open ToDo is to update the Julia documentation deployment, but that has to be @pazner because it involves setting up keys.

Also, I'd like to investigate ICC testing on GitHub Actions.

**Comment by jeremylt** [comment]
@jedbrown, the only reason Noether is failing is because the filepath is too long for the Nek5000 qFunctions. Is there a way to cut down the length of the filepath for these jobs?

We'll also need to remove Travis CI as a 'required' for PRs

**Comment by jeremylt** [comment]
GitLab CI passes now. Just need to sort out the Julia keys

**Comment by pazner** [comment]
> GitLab CI passes now. Just need to sort out the Julia keys

I've got most of this set up on my end, but I don't have access to add secrets keys for GitHub actions.

**Comment by pazner** [comment]
I think the Julia documentation is good to go. There is an option to publish "preview" documentation for PRs that is currently disabled. Do we want to enable that?

Let me know if there are other changes I should make.

**Comment by jedbrown** [comment]
Are the previews linked from the PRs? We use that for ReadTheDocs and I think it's quite useful for review. I'd expect only a modest fraction of PRs will touch Julia docs, but I don't see that as a problem.

**Comment by pazner** [comment]
> Are the previews linked from the PRs? We use that for ReadTheDocs and I think it's quite useful for review. I'd expect only a modest fraction of PRs will touch Julia docs, but I don't see that as a problem.

The preview will be associated with the PR number. I don't think a link from the PR will automatically be created (e.g. as a comment, like codecov. Something like this is probably possible using actions, though). I'm not sure if that's what you are referring to.

**Comment by jeremylt** [comment]
I have a mild preference to put both Julia jobs in the same file, but whichever seems more readable works for me

**Comment by pazner** [comment]
I enabled the previews. For example, for this PR the docs can be found at https://ceed.exascaleproject.org/libCEED-julia-docs/previews/PR658/

@jeremylt, I can squash the Julia commits or would you prefer to do it?

**Comment by pazner** [comment]
> I have a mild preference to put both Julia jobs in the same file, but whichever seems more readable works for me

I had them in the same file, but I just separated them because the triggers are not the same.

**Comment by jeremylt** [comment]
Feel free to squash as you like

**Comment by jeremylt** [comment]
I squashed some of my commits as well. I think we are ready to drop the Travis requirement in the repo settings and merge this PR.

**Review by jedbrown — APPROVED** [review]

**Comment by jedbrown** [comment]
I think I have the required jobs set appropriately now. It seems the GitLab-CI pipelines include the branch name so I don't know how to make it required.

**Pull request merged**
