### PR TITLE
Update CEED_EVAL_DIV/INTERP

### PR DESCRIPTION
**Pull request by rezgarshakeri**
Updated CEED_EVAL_DIV/INTERP to work for H(div) problem.

### CODE REVIEW

**Comment by jeremylt** [comment]
Do we have an operator test with an Hdiv basis using Div and Interp? It would be good to make sure these changes are part of the test suite.

**Comment by rezgarshakeri** [comment]
I have tested before in my Hdiv branch. I just wanted to make my rebase and your review easier, so when we want to merge the Hdiv example there would be no changes in backends.

**Review by jeremylt — APPROVED** [review]
Looks good, knowing you manually tested

**Comment by rezgarshakeri** [comment]
Yeah, I did.

**Pull request merged**
