### PR TITLE
Fluids - Some fixes missing from #1039

### PR DESCRIPTION
**Pull request by LeilaGhaffari**
See https://github.com/CEED/libCEED/pull/1039#discussion_r956733785 and https://github.com/CEED/libCEED/pull/1039#discussion_r956734876.

### CODE REVIEW

**Review by jedbrown — APPROVED** [review]
Thanks. Looks fine to me. I assume you've used grep to check for any stray references to the old names.

**Comment by LeilaGhaffari** [comment]
Yes, I used grep. I'll go ahead and merge this. Thanks!

**Comment by jeremylt** [comment]
We didn't catch this in CI since it isn't running on Noether (see #1058) but this is resulting in failures in this test case for me
```
# Test Name: blasius
# TESTARGS: -ceed {ceed_resource} -test -options_file examples/fluids/blasius.yaml -compare_final_state_atol 2E-11 -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius.bin -ts_max_steps 10 -dm_plex_box_faces 5,10,1
not ok 1 fluids-navierstokes /cpu/self/ref/serial
ok 2 fluids-navierstokes /cpu/self/ref/serial stdout
not ok 3 fluids-navierstokes /cpu/self/ref/serial stderr
# +[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
# +[0]PETSC ERROR: TSStep has failed due to DIVERGED_NONLINEAR_SOLVE, increase -ts_max_snes_failures or make negative to attempt recovery
# +[0]PETSC ERROR: WARNING! There are option(s) set that were not used! Could be the program crashed before they were used or a spelling mistake, etc!
# +[0]PETSC ERROR: Option left: name:-stg_inflow_path value: ./STGInflow_blasius.dat
# +[0]PETSC ERROR: Option left: name:-stg_mean_only value: true
# +[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
# +[0]PETSC ERROR: Petsc Development GIT revision: v3.17.4-1071-g6152e20ae75  GIT Date: 2022-08-15 00:54:59 +0000
# +[0]PETSC ERROR: build/fluids-navierstokes on a arch-cpu-native-mpi named sinensis by jeremy Tue Aug 30 09:35:49 2022
# +[0]PETSC ERROR: Configure options --with-fortran-bindings=0 --download-triangle --download-ctetgen --download-tetgen --with-debugging=1 COPTFLAGS="-O2 -march=native" PETSC_ARCH=arch-cpu-native-mpi --download-cgns --download-exodusii --download-hdf5 --download-metis --download-mumps --download-scalapack --download-netcdf --download-parmetis --download-pnetcdf --download-triangle --download-zlib
# +[0]PETSC ERROR: #1 TSStep() at /home/jeremy/Dev/petsc/src/ts/interface/ts.c:3448
# +[0]PETSC ERROR: #2 TSSolve() at /home/jeremy/Dev/petsc/src/ts/interface/ts.c:3825
# +[0]PETSC ERROR: #3 TSSolve_NS() at /home/jeremy/Dev/libCEED/examples/fluids/src/setupts.c:569
# +[0]PETSC ERROR: #4 main() at /home/jeremy/Dev/libCEED/examples/fluids/navierstokes.c:292
# +[0]PETSC ERROR: PETSc Option Table entries:
# +[0]PETSC ERROR: -bc_inflow 6
# +[0]PETSC ERROR: -bc_outflow 5,4
# +[0]PETSC ERROR: -bc_slip_z 1,2
# +[0]PETSC ERROR: -bc_wall 3
# +[0]PETSC ERROR: -ceed /cpu/self/ref/serial
# +[0]PETSC ERROR: -compare_final_state_atol 2E-11
# +[0]PETSC ERROR: -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius.bin
# +[0]PETSC ERROR: -Ctau_C 0.25
# +[0]PETSC ERROR: -Ctau_E 0.125
# +[0]PETSC ERROR: -Ctau_M 0.25
# +[0]PETSC ERROR: -Ctau_t 1
# +[0]PETSC ERROR: -Ctau_v 36
# +[0]PETSC ERROR: -degree 1
# +[0]PETSC ERROR: -dm_plex_box_faces 5,10,1
# +[0]PETSC ERROR: -dm_plex_box_lower 0,0,0
# +[0]PETSC ERROR: -dm_plex_box_upper 4.2e-3,4.2e-3,5.e-5
# +[0]PETSC ERROR: -dm_plex_dim 3
# +[0]PETSC ERROR: -dm_plex_simplex 0
# +[0]PETSC ERROR: -dm_sparse_localize 0
# +[0]PETSC ERROR: -g 0,0,0
# +[0]PETSC ERROR: -implicit true
# +[0]PETSC ERROR: -output_freq 10
# +[0]PETSC ERROR: -platemesh_nDelta 45
# +[0]PETSC ERROR: -problem blasius
# +[0]PETSC ERROR: -q_extra 0
# +[0]PETSC ERROR: -stab supg
# +[0]PETSC ERROR: -stg_inflow_path ./STGInflow_blasius.dat
# +[0]PETSC ERROR: -stg_mean_only true
# +[0]PETSC ERROR: -stg_use false
# +[0]PETSC ERROR: -test
# +[0]PETSC ERROR: -ts_adapt_type none
# +[0]PETSC ERROR: -ts_dt 0.2e-5
# +[0]PETSC ERROR: -ts_max_steps 10
# +[0]PETSC ERROR: -ts_max_time 1.0e-3
# +[0]PETSC ERROR: -ts_type beuler
# +[0]PETSC ERROR: -wall_comps 1,2,3
# +[0]PETSC ERROR: ----------------End of Error Message -------send entire error message to petsc-maint@mcs.anl.gov----------
# +--------------------------------------------------------------------------
# +MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_SELF
# +with errorcode 91.
# +
# +NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
# +You may or may not see output from other processes, depending on
# +exactly when Open MPI kills them.
# +--------------------------------------------------------------------------
```

**Comment by LeilaGhaffari** [comment]
Hmm, it's not failing for me. Can you build it afresh and try again?

**Comment by jeremylt** [comment]
You're running `make prove search=fluid` at the top level and it is passing?

**Comment by LeilaGhaffari** [comment]
Only with `/cpu/self`. I am running 
```
$ make prove search=fluid PROVE_OPTS=-v BACKENDS='/cpu/self'
make: 'lib' with optional backends: /cpu/self
Testing backends: /cpu/self
prove -v --exec 'tests/tap.sh' fluids-navierstokes
fluids-navierstokes .. 
1..45
# Test Name: blasius
# TESTARGS: -ceed {ceed_resource} -test -options_file examples/fluids/blasius.yaml -compare_final_state_atol 2E-11 -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius.bin -ts_max_steps 10 -dm_plex_box_faces 5,10,1
ok 1 fluids-navierstokes /cpu/self
ok 2 fluids-navierstokes /cpu/self stdout
ok 3 fluids-navierstokes /cpu/self stderr
```

**Comment by jeremylt** [comment]
```
$ make prove search=fluid BACKENDS="/cpu/self" -j PROVE_OPTS=-v
make: 'lib' with optional backends: /cpu/self
Testing backends: /cpu/self
prove -v --exec 'tests/tap.sh' fluids-navierstokes
fluids-navierstokes .. 
1..45
# Test Name: blasius
# TESTARGS: -ceed {ceed_resource} -test -options_file examples/fluids/blasius.yaml -compare_final_state_atol 2E-11 -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius.bin -ts_max_steps 10 -dm_plex_box_faces 5,10,1
not ok 1 fluids-navierstokes /cpu/self
ok 2 fluids-navierstokes /cpu/self stdout
not ok 3 fluids-navierstokes /cpu/self stderr
# +[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
# +[0]PETSC ERROR: TSStep has failed due to DIVERGED_NONLINEAR_SOLVE, increase -ts_max_snes_failures or make negative to attempt recovery
# +[0]PETSC ERROR: WARNING! There are option(s) set that were not used! Could be the program crashed before they were used or a spelling mistake, etc!
# +[0]PETSC ERROR: Option left: name:-stg_inflow_path value: ./STGInflow_blasius.dat
# +[0]PETSC ERROR: Option left: name:-stg_mean_only value: true
# +[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
# +[0]PETSC ERROR: Petsc Development GIT revision: v3.17.4-1168-g96596328e34  GIT Date: 2022-08-29 13:10:12 +0000
# +[0]PETSC ERROR: build/fluids-navierstokes on a ratel-testing-parallel named noether by jeth8984 Tue Aug 30 10:03:15 2022
# +[0]PETSC ERROR: Configure options --download-ctetgen --download-kokkos --download-triangle --with-debugging --with-fortran-bindings=0 --with-hip --with-hip-dir=/opt/rocm --with-hip-target=gfx906 -download-kokkos-kernels COPTFLAGS="-O2 -march=native" HIPOPTFLAGS=-O2 PETSC_ARCH=ratel-testing-parallel
# +[0]PETSC ERROR: #1 TSStep() at /projects/ratel/petsc/src/ts/interface/ts.c:3380
# +[0]PETSC ERROR: #2 TSSolve() at /projects/ratel/petsc/src/ts/interface/ts.c:3746
# +[0]PETSC ERROR: #3 TSSolve_NS() at /projects/ratel/libCEED/examples/fluids/src/setupts.c:569
# +[0]PETSC ERROR: #4 main() at /projects/ratel/libCEED/examples/fluids/navierstokes.c:292
# +[0]PETSC ERROR: PETSc Option Table entries:
# +[0]PETSC ERROR: -bc_inflow 6
# +[0]PETSC ERROR: -bc_outflow 5,4
# +[0]PETSC ERROR: -bc_slip_z 1,2
# +[0]PETSC ERROR: -bc_wall 3
# +[0]PETSC ERROR: -ceed /cpu/self
# +[0]PETSC ERROR: -compare_final_state_atol 2E-11
# +[0]PETSC ERROR: -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius.bin
# +[0]PETSC ERROR: -Ctau_C 0.25
# +[0]PETSC ERROR: -Ctau_E 0.125
# +[0]PETSC ERROR: -Ctau_M 0.25
# +[0]PETSC ERROR: -Ctau_t 1
# +[0]PETSC ERROR: -Ctau_v 36
# +[0]PETSC ERROR: -degree 1
# +[0]PETSC ERROR: -dm_plex_box_faces 5,10,1
# +[0]PETSC ERROR: -dm_plex_box_lower 0,0,0
# +[0]PETSC ERROR: -dm_plex_box_upper 4.2e-3,4.2e-3,5.e-5
# +[0]PETSC ERROR: -dm_plex_dim 3
# +[0]PETSC ERROR: -dm_plex_simplex 0
# +[0]PETSC ERROR: -dm_sparse_localize 0
# +[0]PETSC ERROR: -g 0,0,0
# +[0]PETSC ERROR: -implicit true
# +[0]PETSC ERROR: -output_freq 10
# +[0]PETSC ERROR: -platemesh_nDelta 45
# +[0]PETSC ERROR: -problem blasius
# +[0]PETSC ERROR: -q_extra 0
# +[0]PETSC ERROR: -stab supg
# +[0]PETSC ERROR: -stg_inflow_path ./STGInflow_blasius.dat
# +[0]PETSC ERROR: -stg_mean_only true
# +[0]PETSC ERROR: -stg_use false
# +[0]PETSC ERROR: -test
# +[0]PETSC ERROR: -ts_adapt_type none
# +[0]PETSC ERROR: -ts_dt 0.2e-5
# +[0]PETSC ERROR: -ts_max_steps 10
# +[0]PETSC ERROR: -ts_max_time 1.0e-3
# +[0]PETSC ERROR: -ts_type beuler
# +[0]PETSC ERROR: -wall_comps 1,2,3
# +[0]PETSC ERROR: ----------------End of Error Message -------send entire error message to petsc-maint@mcs.anl.gov----------
# +Abort(91) on node 0 (rank 0 in comm 16): application called MPI_Abort(MPI_COMM_SELF, 91) - process 0
# Test Name: blasius_STG
# TESTARGS: -ceed {ceed_resource} -test -options_file examples/fluids/tests-output/blasius_stgtest.yaml -compare_final_state_atol 2E-11 -compare_final_state_filename examples/fluids/tests-output/fluids-navierstokes-blasius_STG.bin
ok 4 fluids-navierstokes /cpu/self
ok 5 fluids-navierstokes /cpu/self stdout
ok 6 fluids-navierstokes /cpu/self stderr
...
```

**Comment by jedbrown** [comment]
I also see this failure. @LeilaGhaffari I'd suggest bisecting on this test.

**Comment by jeremylt** [comment]
The test first appeared in this PR, so it might be an issue with the test case itself

**Comment by LeilaGhaffari** [comment]
Hmm, I don't know how to fix it without being able to reproduce the error.

**Comment by jeremylt** [comment]
Can you reproduce the issue on Noether?

**Comment by LeilaGhaffari** [comment]
Yes, I just reproduced it on Noether. I am still confused though. Maybe it didn't like the way I set up the test on top of `blasius.yaml`. I ended up creating a new yaml file.

**Pull request merged**
