### PR TITLE
Update the Nek5000 example run process

### PR DESCRIPTION
**Pull request by thilinarmtb**
Now back-end is a run-time parameter. Also, the `run-nek-examples.sh` script
is more polished to accept default arguments.

### CODE REVIEW

**Comment by tzanio** [comment]
This is great @thilinarmtb, thanks!

Once merged, can you update the build example in https://github.com/CEED/web/pull/10?

**Comment by thilinarmtb** [comment]
@tzanio : Will do.

**Comment by thilinarmtb** [comment]
I'm fine merging this as it is unless you guys (@tzanio @jedbrown) have any more comments.

**Comment by tzanio** [comment]
I'm merging this for the demo this morning. @jedbrown, if you have changes, lets do them directly in `master`.

**Pull request merged**
