### PR TITLE
Fix op swarm input access

### PR DESCRIPTION
**Pull request by jeremylt**
@zatkins-dev this fixes the error registered with `petsc-dmswarm`, though I don't see why it this is needed given line `728-730` :thinking: 

Ohh, strike that, I do know why. Once we swap to the memcheck Vector, it exposes that those lines violate the memory access assumptions. I'm still not sure why this isn't an issue with regular operators, but for regular operators we actually call a basis operation, so this isn't an issue there.

### CODE REVIEW

**Review by zatkins-dev — APPROVED** [review]
Looks good to me, with the caveat that we revisit the memory access assumptions later

**Comment by jeremylt** [comment]
I think I want to rework this to reference copy the evector to work as the qvector

**Comment by jeremylt** [comment]
@zatkins-dev I think this is a cleaner fix that avoids the dirty memory access hack

**Review by zatkins-dev — APPROVED** [review]
This is a much cleaner solution, thanks Jeremy!

**Pull request merged**
