### PR TITLE
make: MARCHFLAG: try -march=native, -mcpu=native, then skip (fix #467)

### LINKED ISSUE #467: -mtune=power9 is not working
The makefile doesn't work out of the box on lassen:
```
make: 'lib' with optional backends: /cpu/self/memcheck/serial /cpu/self/memcheck/blocked /cpu/occa /gpu/occa /omp/occa /gpu/cuda/ref /gpu/cuda/reg /gpu/cuda/shared /gpu/cuda/gen
          CC build/interface/ceed-fortran.o
cc1: error: unrecognized argument in option '-mtune=power9'
```
Do you know if there is an easy fix to this?

### PR DESCRIPTION
**Pull request by jedbrown**
I think this will do the trick.

### CODE REVIEW

**Comment by jedbrown** [comment]
The question to me is whether these examples should try to set `OPT` at all, since that can fight with how PETSc was built. For example, I sometimes like to swap between debug and opt `PETSC_ARCH`, and need to remember to `OPT=-O0 -g` to debug the example effectively. What do you think of dropping any attempt to set `OPT` in `examples/petsc/Makefile` and `examples/navier-stokes/Makefile`?

**Comment by jedbrown** [comment]
Cc: @valeriabarra

**Comment by jeremylt** [comment]
For me, the big thing with setting `OPT` is getting good performance from our heavy QFunctions on the CPU. Maybe we leave the option but don't auto populate it? Or am I overestimating how much the optflags help the compiled QFunction?

**Comment by jedbrown** [comment]
Optimization flags can make a big difference. What if we take it out of the `examples/*/Makefile` but pass it from the top-level, as in
```
diff --git i/Makefile w/Makefile
index 79f4fafb..4519e145 100644
--- i/Makefile
+++ w/Makefile
@@ -410,12 +410,12 @@ $(OBJDIR)/nek-bps : examples/nek/bps/bps.usr examples/nek/nek-examples.sh $(libc
 
 $(OBJDIR)/petsc-% : examples/petsc/%.c $(libceed) $(ceed.pc) | $$(@D)/.DIR
 	+$(MAKE) -C examples/petsc CEED_DIR=`pwd` \
-	  PETSC_DIR="$(abspath $(PETSC_DIR))" $*
+	  PETSC_DIR="$(abspath $(PETSC_DIR))" OPT="$(OPT)" $*
 	mv examples/petsc/$* $@
 
 $(OBJDIR)/ns-% : examples/navier-stokes/%.c $(libceed) $(ceed.pc) | $$(@D)/.DIR
 	+$(MAKE) -C examples/navier-stokes CEED_DIR=`pwd` \
-	  PETSC_DIR="$(abspath $(PETSC_DIR))" $*
+	  PETSC_DIR="$(abspath $(PETSC_DIR))" OPT="$(OPT)" $*
 	mv examples/navier-stokes/$* $@
 
 libceed_test.o = $(test_backends.c:%.c=$(OBJDIR)/%.o)
```

**Comment by jedbrown** [comment]
I pushed an update to this strategy. Feel free to merge if you think it's acceptable.

**Pull request merged**
