### PR TITLE
Fix qf fallback cloning

### PR DESCRIPTION
**Pull request by jeremylt**
@v-dobrev, I'm running some additional tests outside of the libCEED test suite, but this should fix the other issue.

### CODE REVIEW

**Comment by v-dobrev** [comment]
Thanks for addressing these issues @jeremylt!

In this PR, I can't easily review the changes, so I'm not in a position to give you an informed approval.

**Comment by jedbrown** [comment]
@v-dobrev Can you confirm that it makes your MFEM build happy?

**Comment by v-dobrev** [comment]
I'm in the middle of something else, so I can't test it right now. If you merge it in `master` it will get tested overnight with MFEM and I can let you know tomorrow. If you prefer to not merge it into `master` before a confirmation that it solves the issue, I can test it tomorrow.

**Comment by jeremylt** [comment]
It seems to fix the issue in Ratel, though manually running the tests is getting a failure in a different test (matrix assembly interestingly enough) that is not showing up in CI, so I'm investigating. This should work though.

**Comment by jeremylt** [comment]
Huh, the bug is only in parallel. But unrelated. This should be good to merge. 

What happened: we automatically pass tests that error with the phrase `Backend does not implement`, and PR #956 accidentally broke assembly on the -gen backends in a way that was accidentally passed by the test suite.

**Review by jedbrown — APPROVED** [review]

**Pull request merged**
