### PR TITLE
Jed/fortran api array

### PR DESCRIPTION
**Pull request by jedbrown**
Fix various Fortran issues including no-copy array access and string length handling.

Supersedes #123.

### CODE REVIEW

**Comment by jedbrown** [comment]
@thilinarmtb Please check the Nek bp1 and bp3 output. I don't know how to verify if it is acceptable or not. It would be very useful to print and test an error so there is something simple and visible in the output.

**Comment by jedbrown** [comment]
Likely #71. #84 is a Fortran fixed-form issue.

**Comment by jeremylt** [comment]
`t304` is still failing unfortunately.

**Comment by jeremylt** [comment]
Found it, it was an error in the test.

**Comment by jeremylt** [comment]
@jedbrown the output I am getting from Nek looks like what I was seeing in the spring, but faster. However, I'll defer to @thilinarmtb 's opinion, as I am far from expert and I don't have my old log files to compare to.

I think we should be able to copy over mfem bp3 okl, but perhaps we want to wait until @dmed256 is happy with where OCCA is at for parsing pointers in the loops?

Is the plan to add Nek to CI? I am not sure if/how it would integrate nicely into the prove system we have now.

**Comment by thilinarmtb** [comment]
@jedbrown: I am travelling today, will review this tonight.

**Comment by thilinarmtb** [comment]
Looks like bp1 and bp3 are both broken although they could be run without segfaults now.
I will try to fix the two examples.

**Comment by jedbrown** [comment]
@thilinarmtb Any progress? Do you want help?

**Pull request merged**
