### PR TITLE
Update nek examples build process

### PR DESCRIPTION
**Pull request by thilinarmtb**
This PR polishes the build process of Nek5000 examples. Rather than having
a copy of `makenek` in the `libCEED` repo, this will use `makenek` shipped with
the Nek5000 directory user points to.

Also, removed some lines automatically added to `SIZE` file by `makenek`.

### CODE REVIEW

**Comment by jedbrown** [comment]
I hope that change to `SIZE` is acceptable to you.  Can you make the `make clean` target actually clean the `examples/nek5000/` directory?

**Comment by thilinarmtb** [comment]
I updated the `make clean` target to clean the `nek5000/examples` directory. 

I am fine with using a `SIZE.in` file to generate the SIZE file.

+1 to merge as it is.

**Comment by thilinarmtb** [comment]
@jedbrown, Do you have any more comments? Otherwise I am fine merging this.

**Comment by thilinarmtb** [comment]
Thank you very much for merging !!

**Pull request merged**
