### PR TITLE
Support for defining the makefile OPT variable in the config.mk file

### PR DESCRIPTION
**Pull request by v-dobrev**
(Small tweak, see title)

### CODE REVIEW

**Comment by v-dobrev** [comment]
I forgot about `make configure` -- I created and edited `config.mk` manually.

Looking at the `Makefile` and what is written to `config.mk`, it looks like `CFLAGS` is written to `config.mk` but then the `Makefile` overwrites the value read from `config.mk`. The thing is that `CFLAGS` is defined by make itself so using `?=` instead of `=` will not work here. One solution could be to include `config.mk` *after* setting the variables in the `Makefile` instead of at the very beginning.

I can add `OPT` to `config.mk` but then we probably want to save `CFLAGS` and the like with `$(value CFLAGS)` instead of `$(CFLAGS)`. Do you want me to do that? Should I also move `-include config.mk` later in the `Makefile`?

**Comment by jedbrown** [comment]
Yeah, that overwriting is not intended. Are you sure `CFLAGS` is defined by `make` and not just a variable in your environment?

**Comment by v-dobrev** [comment]
You are right -- `CFLAGS` is not defined by make -- I did not check, I was assuming it is since it is used by some implicit make rules. I think there still may be an issue with using `CFLAGS ?=` since there are some conditional and unconditional `CFLAGS +=` after that.

**Comment by jedbrown** [comment]
Yeah, we'd have to to either put it in a single statement or split out a `CEED_CFLAGS`.

**Comment by v-dobrev** [comment]
Let me know if you want to me to make any changes.

**Comment by jeremylt** [comment]
superseded by #472

**Pull request closed without merging**
