### PR TITLE
chore: make info returns actual flags

### PR DESCRIPTION
**Pull request by jrwrigh**
Before:
```shell
$ make info
------------------------------------
CC            = gcc
CXX           = g++
FC            = gfortran
CPPFLAGS      = -I./include
CFLAGS        = $(OPT) $(CFLAGS.$(CC_VENDOR)) $(if $(PEDANTIC),$(PEDANTICFLAGS)) $(if $(ASAN),$(AFLAGS))
CXXFLAGS      = $(OPT) $(CXXFLAGS.$(CC_VENDOR)) $(if $(PEDANTIC),$(PEDANTICFLAGS))
FFLAGS        = $(OPT) $(FFLAGS.$(FC_VENDOR)) $(if $(ASAN),$(AFLAGS))
NVCCFLAGS     = -ccbin $(CXX) -Xcompiler "$(OPT)" -Xcompiler -fPIC
HIPCCFLAGS    = $(filter-out $(OMP_SIMD_FLAG),$(OPT)) -fPIC -munsafe-fp-atomics
SYCLFLAGS     = $(SYCL_FLAG) -fPIC -std=c++17 $(filter-out -std=c++11,$(CXXFLAGS)) $(filter-out $(OMP_SIMD_FLAG),$(OPT))
CEED_LDFLAGS  = $(if $(ASAN),$(AFLAGS))
CEED_LDLIBS   = -lm
AR            = ar
[...]
```

After:
```shell
❯ make info
------------------------------------
CC            = gcc
CXX           = g++
FC            = gfortran
CPPFLAGS      = -I./include
CFLAGS        = -O -march=native -g -ffp-contract=fast -fopenmp-simd -fPIC -std=c99 -Wall -Wextra -Wno-unused-parameter -MMD -MP
CXXFLAGS      = -O -march=native -g -ffp-contract=fast -fopenmp-simd -fPIC -std=c++11 -Wall -Wextra -Wno-unused-parameter -MMD -MP
FFLAGS        = -O -march=native -g -ffp-contract=fast -fopenmp-simd -fPIC -cpp -Wall -Wextra -Wno-unused-parameter -Wno-unused-dummy-argument -MMD -MP
NVCCFLAGS     = -ccbin g++ -Xcompiler "-O -march=native -g -ffp-contract=fast -fopenmp-simd" -Xcompiler -fPIC
HIPCCFLAGS    = -O -march=native -g -ffp-contract=fast -fPIC -munsafe-fp-atomics
SYCLFLAGS     =  -fPIC -std=c++17 -O -march=native -g -ffp-contract=fast -fopenmp-simd -fPIC -Wall -Wextra -Wno-unused-parameter -MMD -MP -O -march=native -g -ffp-contract=fast
CEED_LDFLAGS  =
CEED_LDLIBS   = -lm
AR            = ar
[...]
```

### CODE REVIEW

**Review by jeremylt — APPROVED** [review]
I like it. Can you do the same for Ratel?

**Comment by jrwrigh** [comment]
Looks like Ratel already has it, except for `includedir`, `libdir`, and `pkgconfigdir`. Still want it there?

**Comment by jeremylt** [comment]
Sure, might as well round it all out to useful output!

**Comment by jrwrigh** [comment]
https://gitlab.com/micromorph/ratel/-/merge_requests/627

**Pull request merged**
