### PR TITLE
fluids: Add diffusion to advection problem

### PR DESCRIPTION
**Pull request by jrwrigh**
Adds diffusion to the advection problem (now making it a "normal" linear advection-diffusion problem). I've tested locally on an over-resolved advecting sine wave and get the analytical solution within 5 digits of accuracy over 2,000 timesteps.

### CODE REVIEW

**Comment by jrwrigh** [comment]
Not sure what's happening with the ROCM error. It's for a completely different fluids tests, and a BPS test failed, so it's probably unreleated.

**Review by jeremylt — APPROVED** [review]
Just for grins, do we have a cool GIF we can make with this to show off?

**Comment by jeremylt** [comment]
There's a failure on re-run, so we need to sort that out before merging

**Comment by jrwrigh** [comment]
Here's a gif for ya. IDK about cool, but it shows the diffusion dampening the higher frequency mode much faster the the lower frequency mode.
out

**Comment by jrwrigh** [comment]
> There's a failure on re-run, so we need to sort that out before merging

It's non-deterministic both in whether it fails and by the error metric and what backend. Regardless, a third run through passed fine, so this should be fine now.

**Pull request merged**
