### PR TITLE
minor - drop unneeded casts

### PR DESCRIPTION
**Pull request by jeremylt**
oops

### CODE REVIEW

**Review by jrwrigh — APPROVED** [review]

**Comment by jrwrigh** [comment]
For the errors on Noether in the fluids example:
```
[WARNING] yaksa: 1 leaked handle pool objects
```

I've only recently seen those on Aurora. Possibly due to latest PETSc `main`?

**Comment by jeremylt** [comment]
Yeah, looks like PETSc is leaking something somewhere maybe? Its for all PETSc examples

**Comment by jeremylt** [comment]
This isn't expressing in Ratel CI - I wonder if there's something fishy with the int64 builds on Noether?

**Comment by jeremylt** [comment]
Hmm, tried setting the opt flags to O2 since MPI is supposed to clean up everything at higher optimization levels, but it doesn't seem to have helped. This error is, according to my initial research, supposed to show when there is a missing `MPI_Type_Free` https://github.com/pmodels/yaksa/discussions/254

**Comment by jeremylt** [comment]
Confirmed, this only occurs for the int64 build, and not the int32 build

**Pull request merged**
