### PR TITLE
CUDA - fix empty restriction support

### PR DESCRIPTION
**Pull request by jeremylt**
I did an incomplete fix of empty restriction support. This should be the last of it.

@valeriabarra, this branch works fine locally with the benchmarks script.

### CODE REVIEW

**Comment by jeremylt** [comment]
I'll merge when CI finishes.

**Comment by valeriabarra** [comment]
Thanks @jeremylt . I'm testing this branch on OLCF Summit, but the `bps` example is still failing. If it works for you then something must be wrong on my environment, even though I do't know what it might be right now, since I have done everything as usual to compile the library, the examples and run the `benchmark.sh` script.

**Comment by jeremylt** [comment]
Well, could be a completely different bug. I'm testing with `make BACKENDS=/gpu/cuda/gen  benchmarks`

**Comment by jeremylt** [comment]
Yeah, locally I'm seeing out of memory errors for our standard script test sizes for the non /gpu/cuda/gen backeds, which is error code 134.

**Comment by valeriabarra** [comment]
This is the (messy) output of the test run on OLCF Summit
[petsc-bps-bp1-gpucudagen-output.txt](https://github.com/CEED/libCEED/files/4653751/petsc-bps-bp1-gpucudagen-output.txt)

**Comment by valeriabarra** [comment]
But I was testing the `/gpu/cuda/gen` backend

**Comment by jeremylt** [comment]
It's a little strange that the runs are on top of each other. We should only have one test running at at time. Is there corresponding output from the bash?

**Comment by valeriabarra** [comment]
Yes, that looked off. Hold on a sec. I think I see a clearer error in the batch output file

**Comment by valeriabarra** [comment]
Fixed it. I am able to run fine with the` /gpu/cuda/gen` backend now on OLCF Summit

**Pull request merged**
