### PR TITLE
[occa] Updated verbose flag

### PR DESCRIPTION
**Pull request by dmed256**
We can merge this for v0.2.1 since it only impacts `debug` mode, but verbose is fixed now

### CODE REVIEW

**Comment by tzanio** [comment]
I prefer we merge this now.

**Comment by jedbrown** [comment]
Yeah, looks simple enough. I'm happy to merge now.

**Comment by tzanio** [comment]
`All tests successful.`  -- Nice!

**Comment by dmed256** [comment]
@jedbrown Thanks!

**Pull request merged**
