### PR TITLE
Travis - Update to Bionic, Add ARM64 and POWER8 arch

### PR DESCRIPTION
**Pull request by jeremylt**
This fixes issue #408

### CODE REVIEW

**Comment by jeremylt** [comment]
Side note: I am seeing the arm64 Travis builds taking longer on another project of mine. I think it's the nature of their current setup.

ppc64le (IBM Power (8 I think)) and s390x (IBM Z9) are also options, if desired. We might have to change the OPT flags for the Power 8 though (`-mcpu` in place of `-march`).

Any opinion on adding an IBM build as well @jedbrown?

**Comment by jedbrown** [comment]
No value in zSeries, but POWER8 has some merit in helping to avoid any CPU-related hiccups whenever we run on Summit/Lassen. That part has been smooth thus far (to my knowledge, only GPU-related issues), but I wouldn't object to adding it to the build matrix.

**Comment by jeremylt** [comment]
ARM and POWER8 are now working. I am trying to update to Bionic so we can use a newer gcc with better warnings. (The tricky part is Nek)

**Comment by jeremylt** [comment]
All set. We're updated to Bionic with gcc 7.4 and I found a small bug in t504 thanks to the POWER8 testing.

I'll merge once Travis finishes.

**Pull request merged**
