### PR TITLE
qf - allow identity qfunctions to have in and out EVAL_NONE

### PR DESCRIPTION
**Pull request by jeremylt**
I found a use case for this

### CODE REVIEW

**Comment by jeremylt** [comment]
An issue may be showing up for qfunctions with both modes none. Will investigate

**Comment by jeremylt** [comment]
I added operator side changes to accommodate this.

**Comment by jeremylt** [comment]
Note: I did not add anything for handling the code generation backends - I just error as unsupported in this case. Eventually I'd like to add proper support of identity QFs in the code generation backends, and we can bundle this update in there as well.

**Comment by jeremylt** [comment]
somewhere around PR #716 Nek tests stopped running on Noether, but they still work fine locally for me

**Review by jedbrown — APPROVED** [review]

**Pull request merged**
