### PR TITLE
headers - clearify includes to not rely on transitive includes

### PR DESCRIPTION
**Pull request by jeremylt**
This is just a minor (but touches a lot of files) style edit - no actual code changes

### CODE REVIEW

**Comment by jeremylt** [comment]
tragically, not that I have found, but I'm still looking

**Comment by jeremylt** [comment]
Google seems to think that it's a known hard thing to check for and there aren't really any tools to help.

**Comment by jedbrown** [comment]
https://include-what-you-use.org/

**Comment by jeremylt** [comment]
Ready now @jedbrown for squash+merge. There is a lot of manual intervention, so that tool is not good for CI, but it was useful for this PR.

**Review by jedbrown — APPROVED** [review]
LGTM. Is there a convention about ordering and spacing between headers (sometimes there's  newline and sometimes not)? And could you add a developer note about the tool?

**Comment by jeremylt** [comment]
I'll add a note. Most of the files used
* one line of whitespace before and after
* installed headers before local headers
* headers alphabetized but with ceed headers listed first
so I tried to stick to that

**Pull request merged**
