### PR TITLE
Consolidate CUDA backends

### PR DESCRIPTION
**Pull request by nbeams**
This PR removes the cuda-reg backend, moving its deterministic element restrictions to cuda-ref and its basis initialization kernels to cuda-shared (which also used them).  All backends that previously had a delegation to cuda-reg for element restrictions have been switched to cuda-ref.  The hip-ref backend restrictions have been updated to match cuda-ref.

I'm wondering how best to add this to the release notes.  "Deprecated features" doesn't seem right, as we don't really lose any important features with this change.  But it's not really an "interface change" either...

### CODE REVIEW

**Comment by jeremylt** [comment]
I should be able to test locally tomorrow morning.

Perhaps for the release notes:
Removed `/gpu/cuda/reg` backend and transferred core features into `/gpu/cuda/ref` and `/gpu/cuda/shared`

**Comment by valeriabarra** [comment]
> I'm wondering how best to add this to the release notes. "Deprecated features" doesn't seem right, as we don't really lose any important features with this change. But it's not really an "interface change" either...

"Deprecated backends"?

**Comment by jeremylt** [comment]
Ah, I see now. I agree that its totally fair to add a section

**Comment by nbeams** [comment]
> I should be able to test locally tomorrow morning.

I do see failures for cuda-gen, but they are the same ones as in #621, so I'm pretty sure they are unrelated to this PR.

**Comment by nbeams** [comment]
@valeriabarra  and @jeremylt, I tried combining your suggestions in 48a65224c9c55c0983064b1cb736437fa872f5aa.  Will change further as requested, though!

**Review by jeremylt — APPROVED** [review]
LGTM. The only backed I wasn't able to test was MAGMA. Trying to reinstall MAGMA from the master branch is always an adventure, and I'm not currently successfully completing that adventure.

**Comment by nbeams** [comment]
> Trying to reinstall MAGMA from the master branch is always an adventure, and I'm not currently successfully completing that adventure.

Luckily I always test MAGMA before opening a PR (as you would expect, considering) :)

**Comment by nbeams** [comment]
The previous `make style` failure was my fault -- turns out I had the wrong version of `astyle` on the machine where I was doing HIP developtment -- but I'm not sure what's going on with the Travis failures now.  It says `make: icc: Command not found`.

**Comment by jeremylt** [comment]
It appears that Intel might have broke the oneapi installer again. I'm looking into it.

**Comment by jeremylt** [comment]
The Travis failure is due to Intel incorrectly rolling out oneapi 2021.1-beta09

In the Apt package, icc and ipp are 2021.1-beta08 while ifort is 2021.1-beta09, which means only the 'most up to date' package (ifort) is sourced and available after Travis installs oneapi.

**Comment by nbeams** [comment]
Thanks @jeremylt for investigating the Intel issue.

Can someone help me understand the issue with the codecov failure?  When I look at the details, I don't see anything explaining why it would fail.  Under "coverage changes," it says, "Everything is accounted for!"  So how can I figure out what caused the problem?  Am I not looking at the right check?

**Comment by jeremylt** [comment]
I think that's just because you cut the total number of lines in the codebase

**Comment by valeriabarra** [comment]
I don't know.. I'm honestly confused by codecov in #530 too

**Comment by jeremylt** [comment]
I think the issue on that PR might be more CodeCov getting confused because of the age of the branch and the rebases/merges. That branch started before we changed our CodeCov a little bit, which is probably not helping.

**Comment by nbeams** [comment]
Um, I'm not sure what's going on with 443bad0b95654aa4c29e96e8951f664065060564 -- after rebasing, GitHub was still telling me the branch was out of date with main (it wasn't), so I tried clicking on the "update" option to see what would happen, and it made a commit of zero changes to say it merged `main` into the branch?  
If I try to undo this, will it go back to telling me the branch is out of date?

**Comment by jedbrown** [comment]
Just getting to this now. There are two commits in 'main' that are not yet in this branch, so it is "out of date" (but not in a problematic way).

**Comment by nbeams** [comment]
I rebased onto `main` to include the new commits...  🤷‍♀️  I see now that it has a different message than when there are conflicts, though, so I guess I shouldn't have worried about it!

**Comment by nbeams** [comment]
If libCEED v0.7 is going to be released tomorrow, do we want to go ahead and merge this before, or wait until after the release?  (Or close without merging, if we decide not to go through with the consolidation?)

**Comment by jeremylt** [comment]
The plan is to merge this today.

**Comment by nbeams** [comment]
I'm not allowed to merge -- I guess because of the codecov failure?  But I don't know how to fix it since I can't see any files causing the failure...

**Comment by jeremylt** [comment]
Yeah, main is protected and we can't merge with 'Required' tests failing. Jed can override.

**Review by jedbrown — APPROVED** [review]
LGTM. Let me know when you want it merged.

**Comment by jedbrown** [comment]
And just confirming that you want squash-merge?

**Comment by nbeams** [comment]
Sure, squash merge is fine.

**Comment by nbeams** [comment]
I don't think there should be any conflicts with #620, but should I merge from main to make sure (if we will squash this branch anyway)?

**Comment by jeremylt** [comment]
@nbeams should `magma/det` have been removed now that the deterministic restriction is in `cuda/ref`?

**Comment by nbeams** [comment]
No, the standard `magma` backend uses its own element restrictions, which include atomic adds and are not deterministic.  So `magma/det` is still necessary; it just changes which CUDA backend it uses for the element restriction object delegation. 

I suppose in the future we could do testing to compare whether the deterministic `cuda-ref` restrictions actually perform better (or basically the same) and then we could remove the special `det` version and use them all the time...

**Pull request merged**
