### PR TITLE
Interface - use __restrict__ for C++ compatibility

### PR DESCRIPTION
**Pull request by jeremylt**
@nbeams, does this fix the issue you were having with building the CUDA backends?

### CODE REVIEW

**Comment by jedbrown** [comment]
If you do this, you can also revert 2517cf59045249613f75fff00c6f061afde59f66. Alternatively, do what most system headers do and use `__restrict`, which is supported by most C++ compilers.

**Comment by jeremylt** [comment]
@jedbrown, I updated it to use `__restrict__`.

**Comment by nbeams** [comment]
I added the change for the `t` parameter as well; now it's building properly.  Thanks!

**Comment by jeremylt** [comment]
Ah yes. Thank you.

**Pull request merged**
