### PR TITLE
WIP: Fluids - Automate mesh generation for boundary layer

### PR DESCRIPTION
**Pull request by amandashack**

### CODE REVIEW

**Comment by jedbrown** [comment]
Hi @amandashack :wave: I hope you're enjoying break. Can you please let us know if you plan to get back to this, and if so, on what timeline?

**Comment by knepley** [comment]
@jedbrown Note that now you can do that with a `DMPlexTransform`. You mark the cells you want to split with a label, and you can refine them normal to the boundary, or you can extrude. I have several tests of this now.

**Comment by jedbrown** [comment]
@knepley Yeah, this branch is intended to create a mesh with element size versus fraction of the computational domain that looks similar to the figure below, but with the transition points (from viscous sublayer to turbulent BL to far-field) and aspect ratios controllable in intuitive ways using plus-units. This would be a nice feature to upstream to PETSc once it's shown to be useful here.
image

**Comment by amandashack** [comment]
Hi @jedbrown yes I plan to work on this over break. My goal is to have it completed by the time classes start back up!

**Comment by jedbrown** [comment]
:wave: Hi, @amandashack. Just checking in on this, if you're still planning to finish and if you have what you need to do so? Completing this would make it easier to conduct accuracy-efficiency experiments for turbulent flow like you see in this clip.

[ROPI_OutView.webm](https://user-images.githubusercontent.com/3303/211728418-1052dac3-4842-4999-9d1e-ba92d838db85.webm)

**Comment by amandashack** [comment]
Hi @jedbrown, Leila is on vacation so we are meeting next week to work on this. I have shared with her some notes on where I am at. I think after we meet on Monday or Tuesday I will reach out to you to let you know where we're at, ask any questions we may have, and give you a timeline for finishing.

**Comment by jedbrown** [comment]
Sounds good. The high order solvers are much improved now so this design space will get interesting.

**Comment by jeremylt** [comment]
Closing in preparation for the HONEE move, but re-open (here or there) if we want to revive this (its been more than a year)

**Pull request closed without merging**
