### PR TITLE
Update postprocessing scripts

### PR DESCRIPTION
**Pull request by valeriabarra**
This very small PR updates the post-processing scripts after that the command line option "qextra" was removed in PR #243

### CODE REVIEW

**Comment by jeremylt** [comment]
You can still specify qextra as a runtime option, but it is filled in automatically if you specify the BP unless you a set it. BP 5/6 have only qextra=1. Setting it in the BP script is redundant.

**Comment by jedbrown** [comment]
Maybe I'm missing something, but can we ensure that it appears somewhere in the output and that the postprocessing script parses it from the output rather than assuming that it has not been changed by the user?

Regarding plotting/postprocessing, we should work toward a solution where we only parse output from the various files and return a pandas dataframe with one row per observation. That can be written as CSV or consumed by a single plotter that will work for all the benchmarks and implementations (MFEM, Nek, etc.). That may be an issue for https://github.com/ceed/benchmarks, however.

**Comment by jeremylt** [comment]
We could add a way to add extra flags through the benchmark script, which would then be picked up by the plotting script and added to the plots if needed. Always adding qextra makes messy plots, IMHO.

It would be lovely to rework the plotting scripts. It looks like in the benchmark repo they slightly customized the scripts to each package, so updating all of the slightly different scripts will take some work. Perhaps we should make a solution here and then take it to the benchmarks repo.

**Comment by jedbrown** [comment]
I guess what I mean is that the output when using `-benchmark` should include the full specification, such that we don't need to know the input arguments or maintain consistency in defaults. I.e., there should be an explicit statement containing P and Q.

Then, the plotting script can drop mention of O when it uses the standard benchmark spec, but we won't get misleading plots if we were to run a nonstandard configuration.

**Comment by jeremylt** [comment]
The BP name is an option that `petsc-bps.c` keeps track of. We could output it as part of our revamp of the scripts: #263

**Pull request merged**
