### PR TITLE
Live Doxygen documentation

### PR DESCRIPTION
**Pull request by tzanio**
Once merged, the Doxygen documentation will be automatically build and served at https://codedocs.xyz/ceed/libCEED on any push to `master`.

Live preview here:

https://codedocs.xyz/tzanio/libCEED2/

### CODE REVIEW

**Comment by tzanio** [comment]
Here is how it will look like:

https://codedocs.xyz/tzanio/libCEED2/

**Comment by v-dobrev** [comment]
The local doxygen build fails. I think it should be fixed before merging.

**Comment by tzanio** [comment]
Can you elaborate? `doxygen doc/Doxyfile` works fine on my Mac.

**Comment by v-dobrev** [comment]
It's not clear that is how a user/developer is supposed to build the docs. I just tried `cd doc; doxygen`. It'll best to add a makefile target for building the docs.

Also, building that way the output directory, `html`, is inside the main directory, contrary to what the `distclean` target suggests.

**Comment by v-dobrev** [comment]
This is probably not that important right now but for mathjax we should change the CDN website as explained in the [mathjax docs](https://docs.mathjax.org/en/latest/start.html#using-a-content-delivery-network-cdn). LLNL has CDN with mathjax installed at [https://cdn.llnl.gov/mathjax/2.7.2](https://cdn.llnl.gov/mathjax/2.7.2)

**Comment by tzanio** [comment]
> This is probably not that important right now but for mathjax we should change the CDN website as explained in the mathjax docs. LLNL has CDN with mathjax installed at https://cdn.llnl.gov/mathjax/2.7.2

I'm OK with making this change in this PR... @jedbrown what do you think?

**Comment by jedbrown** [comment]
Doesn't matter to me.

**Comment by tzanio** [comment]
Fixed local build, see https://github.com/CEED/libCEED/pull/34#issuecomment-366867034

**Comment by jedbrown** [comment]
Do you know why the broken `\ref` warnings?

```
/home/jed/src/libceed/README.md:9: warning: unable to resolve reference to `doc/libCEED.md' for \ref command                                                                                  
/home/jed/src/libceed/README.md:21: warning: unable to resolve reference to `doc/libCEED.md' for \ref command
```

**Comment by tzanio** [comment]
> /home/jed/src/libceed/README.md:9: warning: unable to resolve reference to `doc/libCEED.md' for \ref command                                                                                  
> /home/jed/src/libceed/README.md:21: warning: unable to resolve reference to `doc/libCEED.md'

This is on purpose -- Doxygen doesn't render that Markdown file well, plus I felt it doesn't fit naturally in a Doxygen documentation.

One can include it by adding `doc` to the `INPUT` section: https://github.com/CEED/libCEED/pull/34/files#diff-ef0172b9c0ab10af3b7f842de2b9d5caR798

**Comment by jedbrown** [comment]
Huh, doxygen is gross.  Thanks.

**Comment by v-dobrev** [comment]
@tzanio, I still think that there should be a makefile target, e.g. `make doc` or `make docs`.

**Comment by tzanio** [comment]
@v-dobrev: `make doc` and `https://cdn.llnl.gov/mathjax/2.7.2` done.

**Comment by jedbrown** [comment]
Is this the page I should be looking at for the web rendering? Can we have something other than a blank front page? Even just the list of modules would be better than nothing.

https://codedocs.xyz/tzanio/libCEED/

**Comment by tzanio** [comment]
@jedbrown: no, look at https://codedocs.xyz/tzanio/libCEED2

**Comment by v-dobrev** [comment]
Thanks, @tzanio!

**Comment by v-dobrev** [comment]
I tried viewing the documentation at https://codedocs.xyz/ceed/libCEED but I get "Not found". Is there something else that we need to do after merging?

**Comment by tzanio** [comment]
It should be live now at https://codedocs.xyz/CEED/libCEED/

**Pull request merged**
