### PR TITLE
Add -include directive to Makefile 

### PR DESCRIPTION
**Pull request by valeriabarra**
Added -include directive to top-level Makefile to allow easy import of custom build configurations (harmless if file config.mk does not exist)

### CODE REVIEW

**Comment by valeriabarra** [comment]
Thanks for adding that. It looks good. I also had to add `CUDA_LIB_DIR_STUBS` (please see my [comment](https://github.com/CEED/libCEED/pull/249#issuecomment-498050154) ). Would it be good to add it here as well?

**Comment by jeremylt** [comment]
Ready to merge?

**Comment by valeriabarra** [comment]
> Ready to merge?

Currently testing. Will merge when done.

**Comment by valeriabarra** [comment]
@jedbrown I've added  `@: > config.mk` so that if one runs  `make configure` multiple times, it does not append to the same  `config.mk` file multiple times. Moreover, I've added the `-a` option to the tee command for CC, FC, and NVCC. If it looks ok to you, I can merge it.

**Comment by jedbrown** [comment]
Yeah, all but the first line was meant to be `tee -a`. Your solution is fine too, and less error-prone if one were to reorder. I pushed one more minor commit, and it should be ready to merge.

**Pull request merged**
