### PR TITLE
Solids leak

### PR DESCRIPTION
**Pull request by rezgarshakeri**
Issue https://github.com/CEED/libCEED/issues/983

### CODE REVIEW

**Comment by rezgarshakeri** [comment]
FunctionList is destroyed. I need to fix the leaks in Multigrid
```
==409088== Invalid write of size 1
==409088==    at 0x69170FE: __vsprintf_internal (iovsprintf.c:97)
==409088==    by 0x69BFE4A: __sprintf_chk (sprintf_chk.c:40)
==409088==    by 0x5ED22BD: sprintf (stdio2.h:36)
==409088==    by 0x5ED22BD: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1107)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==  Address 0x104e0112 is 0 bytes after a block of size 18 alloc'd
==409088==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==409088==    by 0x5ED9DE9: CeedCallocArray (ceed.c:251)
==409088==    by 0x5ED2271: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1106)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088== 
==409088== Invalid read of size 1
==409088==    at 0x5ED7B0C: CeedOperatorSetName (ceed-operator.c:1192)
==409088==    by 0x5ED22D2: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1109)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==  Address 0x104e0112 is 0 bytes after a block of size 18 alloc'd
==409088==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==409088==    by 0x5ED9DE9: CeedCallocArray (ceed.c:251)
==409088==    by 0x5ED2271: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1106)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088== 
==409088== Invalid write of size 1
==409088==    at 0x69170FE: __vsprintf_internal (iovsprintf.c:97)
==409088==    by 0x69BFE4A: __sprintf_chk (sprintf_chk.c:40)
==409088==    by 0x5ED2337: sprintf (stdio2.h:36)
==409088==    by 0x5ED2337: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1115)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==  Address 0x104e0171 is 0 bytes after a block of size 17 alloc'd
==409088==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==409088==    by 0x5ED9DE9: CeedCallocArray (ceed.c:251)
==409088==    by 0x5ED2305: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1114)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088== 
==409088== Invalid read of size 1
==409088==    at 0x5ED7B0C: CeedOperatorSetName (ceed-operator.c:1192)
==409088==    by 0x5ED234C: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1117)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==  Address 0x104e0171 is 0 bytes after a block of size 17 alloc'd
==409088==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==409088==    by 0x5ED9DE9: CeedCallocArray (ceed.c:251)
==409088==    by 0x5ED2305: CeedSingleOperatorMultigridLevel (ceed-preconditioning.c:1114)
==409088==    by 0x5ECFD77: CeedOperatorMultigridLevelCreateTensorH1 (ceed-preconditioning.c:2107)
==409088==    by 0x5ECFAAC: CeedOperatorMultigridLevelCreate (ceed-preconditioning.c:2029)
==409088==    by 0x1369EB: SetupLibceedLevel (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x125869: SetupLibceedLevel_ElasFSInitialNH1 (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088==    by 0x1171D0: main (in /home/rezgar/libCEED/examples/solids/elasticity)
==409088== 
```

**Comment by rezgarshakeri** [comment]
> 

Problem is in these two blocks in `ceed-preconditioning.c`
```
// Clone name
  bool has_name = op_fine->name;
  size_t name_len = op_fine->name ? strlen(op_fine->name) : 0;
  ierr = CeedOperatorSetName(*op_coarse, op_fine->name); CeedChk(ierr);
  {
    char *prolongation_name;
    ierr = CeedCalloc(18 + name_len, &prolongation_name); CeedChk(ierr);
    sprintf(prolongation_name, "prolongation%s%s", has_name ? " for " : "",
            op_fine->name);
    ierr = CeedOperatorSetName(*op_prolong, prolongation_name); CeedChk(ierr);
    ierr = CeedFree(&prolongation_name); CeedChk(ierr);
  }
  {
    char *restriction_name;
    ierr = CeedCalloc(17 + name_len, &restriction_name); CeedChk(ierr);
    sprintf(restriction_name, "restriction%s%s", has_name ? " for " : "",
            op_fine->name);
    ierr = CeedOperatorSetName(*op_restrict, restriction_name); CeedChk(ierr);
    ierr = CeedFree(&restriction_name); CeedChk(ierr);
  }
```

**Comment by jeremylt** [comment]
Ah, need to account for the possibility that the fine operator has a null pointer for a name here.
```
    sprintf(prolongation_name, "prolongation%s%s", has_name ? " for " : "",
            op_fine->name);
```

**Review by jedbrown — APPROVED** [review]
Looks good. In the future, it's nice to explain why in the commit message "fix invalid field access in sprintf" since that's more relevant than how you did it (with a ternary operator).

**Pull request merged**
