### PR TITLE
CUDA - enable multiple output modes for cuda/gen

### LINKED ISSUE #374: CUDA Gen Multiple Output Mode Error
The backend `/gpu/cuda/gen` errors when an operator has several `CeedEvalMode` writing to the same vector.

To reproduce, see `t532-operator`

Valgrind stack trace:
```
==32498== Process terminating with default action of signal 6 (SIGABRT): dumping core
==32498==    at 0xC0D9207: raise (in /usr/lib64/libc-2.17.so)
==32498==    by 0xC0DA8F7: abort (in /usr/lib64/libc-2.17.so)
==32498==    by 0x4E4B0FB: CeedErrorAbort (ceed.c:143)
==32498==    by 0x4E4B1D0: CeedErrorImpl (ceed.c:108)
==32498==    by 0x4E4AA73: CeedVectorGetArray (ceed-vec.c:196)
==32498==    by 0x4E5D46C: CeedOperatorApply_Cuda_gen (ceed-cuda-gen-operator.c:91)
==32498==    by 0x401A7A: main (t532-operator.c:132)
```

`/gpu/cuda/gen` attempts to gain write access to the same vector twice, once for `CEED_EVAL_INTERP` and once for `CEED_EVAL_GRAD`.

This bug is not present in any other CUDA backend.

### PR DESCRIPTION
**Pull request by jeremylt**
This is a patch. We will want to make a more efficient solution in the long term.

I'm running the test suite now.

Fixes #374

### CODE REVIEW

**Comment by jedbrown** [comment]
Does the Navier-Stokes example work with this change?

**Comment by jeremylt** [comment]
This fixes #374, I'm testing it for NS next

**Comment by jeremylt** [comment]
Yeah, we will want to enable a more optimized solution in the future, but this fixes the behavior at least.

**Comment by jeremylt** [comment]
@jedbrown, NS now runs on cuda/gen

**Pull request merged**
