### PR TITLE
CITING.md

### PR DESCRIPTION
**Pull request by valeriabarra**
This small PR adds a CITING.md file at top level. It is ~~upstream of~~ needed for #446 , where I'm going to create a symbolic link, similarly to what we did for the `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` files.

I know there is no useful information on this file yet. It's needed as a placeholder for now for the symbolic link. We will update it as soon as we have the proper references (can include BiBTeX citations and add bib files as well, if we prefer later on).

### CODE REVIEW

**Comment by jedbrown** [comment]
What do you mean by "upstream of #446"? Usually that would mean that `user-manual` would merge into this. Is it a problem to wait or leave an `@misc` for the website until we have a real publication?

**Comment by valeriabarra** [comment]
> What do you mean by "upstream of #446"? Usually that would mean that `user-manual` would merge into this. Is it a problem to wait or leave an `@misc` for the website until we have a real publication?

Ah no sorry for the confusion! I didn't mean that `user-manual` will be merged into this one. 
We can leave a `@misc`. Which page exactly you want me to refer to?

**Comment by jedbrown** [comment]
https://github.com/ceed/libceed?

**Comment by valeriabarra** [comment]
Lol, I accidentally tagged a user whose handle is misc this way.

**Comment by valeriabarra** [comment]
> Lol, I accidentally tagged a user whose handle is misc this way.

Amended commit message

**Comment by valeriabarra** [comment]
@jedbrown is this good as is?

**Comment by valeriabarra** [comment]
> Pop it in a verbatim code block. It doesn't render how you want: https://github.com/CEED/libCEED/blob/valeria/add-CITING.md/CITING.md

@jedbrown done. If it was me, I'd actually put the `.bib` file in a directory named, let's say `refs/`, `references/`, `bib/`, `bibliography/`, or however we want to call it. For people who use library management tools, e.g., [zotero](https://www.zotero.org/), it is much more convenient to import a `.bib` file than having to copy and paste the metadata info.

**Comment by valeriabarra** [comment]
@jedbrown let me know what you think. Redundant info or actually useful?

**Comment by jedbrown** [comment]
Seems fine.  A year is helpful for APA-style citations.  I'd probably use "lib{CEED} development site" for the title.  Use your judgment.

**Pull request merged**
